const obj = {
  date: "23.11.2023",
  bank: "PB",
  baseCurrency: 980,
  baseCurrencyLit: "UAH",
  exchangeRate: [
    {
      baseCurrency: "UAH",
      currency: "AUD",
      saleRateNB: 23.6675,
      purchaseRateNB: 23.6675,
    },
    {
      baseCurrency: "UAH",
      currency: "AZN",
      saleRateNB: 21.2287,
      purchaseRateNB: 21.2287,
    },
    {
      baseCurrency: "UAH",
      currency: "BYN",
      saleRateNB: 13.1097,
      purchaseRateNB: 13.1097,
    },
    {
      baseCurrency: "UAH",
      currency: "CAD",
      saleRateNB: 26.294,
      purchaseRateNB: 26.294,
    },
    {
      baseCurrency: "UAH",
      currency: "CHF",
      saleRateNB: 40.8073,
      purchaseRateNB: 40.8073,
      saleRate: 42.43,
      purchaseRate: 40.71,
    },
    {
      baseCurrency: "UAH",
      currency: "CNY",
      saleRateNB: 5.0442,
      purchaseRateNB: 5.0442,
    },
    {
      baseCurrency: "UAH",
      currency: "CZK",
      saleRateNB: 1.6069,
      purchaseRateNB: 1.6069,
      saleRate: 1.63,
      purchaseRate: 1.59,
    },
    {
      baseCurrency: "UAH",
      currency: "DKK",
      saleRateNB: 5.2765,
      purchaseRateNB: 5.2765,
    },
    {
      baseCurrency: "UAH",
      currency: "EUR",
      saleRateNB: 39.3352,
      purchaseRateNB: 39.3352,
      saleRate: 41.05,
      purchaseRate: 40.05,
    },
    {
      baseCurrency: "UAH",
      currency: "GBP",
      saleRateNB: 45.2124,
      purchaseRateNB: 45.2124,
      saleRate: 46.93,
      purchaseRate: 45.0,
    },
    {
      baseCurrency: "UAH",
      currency: "GEL",
      saleRateNB: 13.4365,
      purchaseRateNB: 13.4365,
    },
    {
      baseCurrency: "UAH",
      currency: "HUF",
      saleRateNB: 0.103354,
      purchaseRateNB: 0.103354,
    },
    {
      baseCurrency: "UAH",
      currency: "ILS",
      saleRateNB: 9.6766,
      purchaseRateNB: 9.6766,
    },
    {
      baseCurrency: "UAH",
      currency: "JPY",
      saleRateNB: 0.24248,
      purchaseRateNB: 0.24248,
    },
    {
      baseCurrency: "UAH",
      currency: "KZT",
      saleRateNB: 0.078841,
      purchaseRateNB: 0.078841,
    },
    {
      baseCurrency: "UAH",
      currency: "MDL",
      saleRateNB: 2.03,
      purchaseRateNB: 2.03,
    },
    {
      baseCurrency: "UAH",
      currency: "NOK",
      saleRateNB: 3.3629,
      purchaseRateNB: 3.3629,
    },
    {
      baseCurrency: "UAH",
      currency: "PLN",
      saleRateNB: 9.0142,
      purchaseRateNB: 9.0142,
      saleRate: 9.5,
      purchaseRate: 8.95,
    },
    {
      baseCurrency: "UAH",
      currency: "SEK",
      saleRateNB: 3.4545,
      purchaseRateNB: 3.4545,
    },
    {
      baseCurrency: "UAH",
      currency: "SGD",
      saleRateNB: 26.906,
      purchaseRateNB: 26.906,
    },
    {
      baseCurrency: "UAH",
      currency: "TMT",
      saleRateNB: 10.3661,
      purchaseRateNB: 10.3661,
    },
    {
      baseCurrency: "UAH",
      currency: "TRY",
      saleRateNB: 1.2511,
      purchaseRateNB: 1.2511,
    },
    {
      baseCurrency: "UAH",
      currency: "UAH",
      saleRateNB: 1.0,
      purchaseRateNB: 1.0,
    },
    {
      baseCurrency: "UAH",
      currency: "USD",
      saleRateNB: 36.0675,
      purchaseRateNB: 36.0675,
      saleRate: 37.55,
      purchaseRate: 37.05,
    },
    {
      baseCurrency: "UAH",
      currency: "UZS",
      saleRateNB: 0.0029655,
      purchaseRateNB: 0.0029655,
    },
    {
      baseCurrency: "UAH",
      currency: "XAU",
      saleRateNB: 72208.58,
      purchaseRateNB: 72208.58,
    },
  ],
};
